name: pagatodo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.2
  chopper: ^7.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  go_router: ^10.1.3
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  local_auth_ios: ^1.1.4
  local_auth_android: ^1.0.34
  local_auth_platform_interface: ^1.0.8
  logger: ^2.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  rive: ^0.11.16
  flex_color_scheme: ^7.3.1
  formz: ^0.6.0
  cupertino_icons: ^1.0.6
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  chopper_generator: ^7.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/rive/

flutter_gen:
  output: lib/src/common/assets

  # Optional
  integrations:
    flutter_svg: true