name: dart

on:
  pull_request:
    paths:
      - ".github/workflows/dart.yml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dart.yml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: 3.13.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .